from py.bitmex import Bitmex
from py.config import *

b = Bitmex(api_key=api_key_test, api_secret=api_secret_test)

results = b.order(method='POST', symbol='XBTUSD', orderType='Market', orderQty=1)
{'orderID': '6ad368e3-0a17-dce4-3129-831ea44bd5b4',
 'clOrdID': '',
 'clOrdLinkID': '',
 'account': 246037,
 'symbol': 'XBTUSD',
 'side': 'Buy',
 'simpleOrderQty': None,
 'orderQty': 1,
 'price': 8212.5,
 'displayQty': None,
 'stopPx': None,
 'pegOffsetValue': None,
 'pegPriceType': '',
 'currency': 'USD',
 'settlCurrency': 'XBt',
 'ordType': 'Market',
 'timeInForce': 'ImmediateOrCancel',
 'execInst': '',
 'contingencyType': '',
 'exDestination': 'XBME',
 'ordStatus': 'Filled',
 'triggered': '',
 'workingIndicator': False,
 'ordRejReason': '',
 'simpleLeavesQty': None,
 'leavesQty': 0,
 'simpleCumQty': None,
 'cumQty': 1,
 'avgPx': 8212,
 'multiLegReportingType': 'SingleSecurity',
 'text': 'Submitted via API.',
 'transactTime': '2019-10-21T19:47:46.050Z',
 'timestamp': '2019-10-21T19:47:46.050Z'}


results = b.order(method='POST', symbol='XBTUSD', orderType='Limit', orderQty=1, price=8100)
{'orderID': '9ce85eef-307d-a676-e37e-1d9152dbd317',
 'clOrdID': '',
 'clOrdLinkID': '',
 'account': 246037,
 'symbol': 'XBTUSD',
 'side': 'Buy',
 'simpleOrderQty': None,
 'orderQty': 1,
 'price': 8100,
 'displayQty': None,
 'stopPx': None,
 'pegOffsetValue': None,
 'pegPriceType': '',
 'currency': 'USD',
 'settlCurrency': 'XBt',
 'ordType': 'Limit',
 'timeInForce': 'GoodTillCancel',
 'execInst': '',
 'contingencyType': '',
 'exDestination': 'XBME',
 'ordStatus': 'New',
 'triggered': '',
 'workingIndicator': True,
 'ordRejReason': '',
 'simpleLeavesQty': None,
 'leavesQty': 1,
 'simpleCumQty': None,
 'cumQty': 0,
 'avgPx': None,
 'multiLegReportingType': 'SingleSecurity',
 'text': 'Submitted via API.',
 'transactTime': '2019-10-21T19:48:45.593Z',
 'timestamp': '2019-10-21T19:48:45.593Z'}
